document.writeln("<div align=\"center\"><table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"85%\">          <tr>            ");
document.writeln("			<td width=\"100%\" background=\"http:\/\/www.xh-yingli.com\/aboutus\/images\/ll.gif\">              <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">                <tr>                  <td width=\"100%\" class=\"p92\" align=\"center\" height=\"37\" style=\"border-bottom:1 solid #3A8ABA\">                    <p align=\"left\">&nbsp;<font color=\"#FFFFFF\">·<a href=\"http:\/\/www.xh-yingli.com\/products\/pro1.htm\" class=\"4\">CLG-361履带式气动钻机<\/a><\/font><\/td>                <\/tr>                <tr>                  <td width=\"100%\" class=\"p92\" align=\"center\" height=\"37\" style=\"border-bottom:1 solid #3A8ABA\">                                        <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"p92\">                      <tr>                        <td width=\"100%\" bordercolor=\"#1A84CA\" bgcolor=\"#177BBD\" height=\"28\">&nbsp;&nbsp;&nbsp;&nbsp;                            ");
document.writeln("				<a href=\"http:\/\/www.xh-yingli.com\/products\/pro1.htm\" class=\"4\">CLG-361产品特点<\/a><\/td>                      <\/tr>                      <tr>                        <td width=\"100%\" bordercolor=\"#1A84CA\" bgcolor=\"#177BBD\" height=\"28\">&nbsp;&nbsp;&nbsp;&nbsp;                            ");
document.writeln("					<a href=\"http:\/\/www.xh-yingli.com\/products\/pro1b.htm\" class=\"4\">CLG-361技术参数<\/a><\/td>                      <\/tr>                    <\/table>                  ");
document.writeln("							<div align=\"center\">");
document.writeln("								<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">");
document.writeln("									<tr>");
document.writeln("										<td height=\"37\">");
document.writeln("										<p class=\"p92\">&nbsp;<font color=\"#FFFFFF\">·<a class=\"4\" href=\"http:\/\/www.xh-yingli.com\/products\/pro2_120.htm\">YL851A液压履带式潜孔钻机<\/a><\/font><\/td>");
document.writeln("									<\/tr>");
document.writeln("									<\/table>");
document.writeln("							<\/div>");
document.writeln("						<\/td>                <\/tr>                <tr>                  <td width=\"100%\" class=\"p92\" align=\"center\" height=\"37\" style=\"border-bottom:1 solid #3A8ABA\">                                        <p align=\"left\">&nbsp;<font color=\"#FFFFFF\">·<a href=\"http:\/\/www.xh-yingli.com\/products\/pro2.htm\" class=\"4\">YL851液压履带式潜孔钻机<\/a><\/font><\/td>                <\/tr>                <tr>                  <td width=\"100%\" class=\"p92\" align=\"center\" height=\"37\" style=\"border-bottom:1 solid #3A8ABA\">                                        ");
document.writeln("						<p align=\"left\">&nbsp;<font color=\"#FFFFFF\">·<a href=\"http:\/\/www.xh-yingli.com\/products\/pro3.htm\" class=\"4\">钻机配件<\/a><\/font><\/td>                <\/tr>                <tr>                  <td width=\"100%\" class=\"p92\" align=\"center\" height=\"37\" style=\"border-bottom:1 solid #3A8ABA\">                                        ");
document.writeln("						<p align=\"left\">&nbsp;<font color=\"#FFFFFF\">·<a href=\"http:\/\/www.xh-yingli.com\/products\/pro4.htm\" class=\"4\">空压机<\/a><\/font><\/td>                <\/tr>                <tr>                  <td width=\"100%\" class=\"p92\" align=\"center\" height=\"37\" style=\"border-bottom:1 solid #3A8ABA\">                                        ");
document.writeln("							<p align=\"left\">&nbsp;<font color=\"#FFFFFF\">·<a href=\"http:\/\/www.xh-yingli.com\/products\/pro5.htm\" class=\"4\">钻具<\/a><\/font><\/td>                <\/tr>              <\/table>        <center>                                        　<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">                <tr>                  ");
document.writeln("				<td width=\"100%\" height=\"130\"><\/td>                <\/tr>              <\/table>              <\/center><\/td>          <\/tr>        <\/table><\/div>")