<%@ page language="java" import="java.util.*" contentType="text/html;charset=UTF-8" pageEncoding="UTF-8"%>
<%@page import="com.jerehnet.util.common.CommonString"%><%@page import="com.jerehnet.util.dbutil.DBHelper"%>
<%@page import="java.sql.Connection"%><%@ taglib uri="/WEB-INF/classes/oscache.tld" prefix="cache"%><%
String factoryid = CommonString.getFormatPara(request.getParameter("factory_id")) ; // 品牌id 
String catalog = CommonString.getFormatPara(request.getParameter("catalog")) ; // 
String tonandmeter = CommonString.getFormatPara(request.getParameter("tonandmeter")) ;
String order = CommonString.getFormatPara(request.getParameter("order")) ;
String flag = CommonString.getFormatPara(request.getParameter("flag")) ;
String cachekey = factoryid+catalog+tonandmeter+order+flag + "brands";
%>
<cache:cache cron="*/1 * * * *">
                 <div class="pllist"> <a target="_top" class="plfl" href="/101-<%=factoryid%>-0.htm"> <strong style="color:#3355AC"> 土方机械</strong> </a> <br>
                  <a target="_top" href="/101003-<%=factoryid%>-0.htm"> 推土机 </a> <a target="_top" href="/101002-<%=factoryid%>-0.htm"> 装载机 </a> <a target="_top" href="/101001-<%=factoryid%>-0.htm"> 挖掘机 </a> <a target="_top" href="/101005-<%=factoryid%>-0.htm"> 平地机 </a> <a target="_top" href="/101004-<%=factoryid%>-0.htm"> 铲运机 </a> <a target="_top" href="/101008-<%=factoryid%>-0.htm"> 自卸卡车 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/102-<%=factoryid%>-0.htm"> <strong style="color:#3355AC">起重机</strong> </a> <br>
                  <a target="_top" href="/102013-<%=factoryid%>-0.htm"> 桥梁式起重机 </a> <a target="_top" href="/102012-<%=factoryid%>-0.htm"> 伸缩臂叉装机 </a> <a target="_top" href="/102002-<%=factoryid%>-0.htm"> 塔式起重机 </a> <a target="_top" href="/102011-<%=factoryid%>-0.htm"> 施工升降机 </a> <a target="_top" href="/102010-<%=factoryid%>-0.htm"> 高空作业车 </a> <a target="_top" href="/102007-<%=factoryid%>-0.htm"> 汽车起重机 </a> <a target="_top" href="/102008-<%=factoryid%>-0.htm"> 履带式起重机 </a> <a target="_top" href="/102006-<%=factoryid%>-0.htm"> 随车起重机 </a> <a target="_top" href="/102003-<%=factoryid%>-0.htm"> 高空作业平台 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/103-<%=factoryid%>-0.htm"><strong style="color:#3355AC"> 混凝土机械</strong> </a> <br>
                  <a target="_top" href="/103008-<%=factoryid%>-0.htm"> 干粉砂浆生产设备 </a> <a target="_top" href="/103009-<%=factoryid%>-0.htm"> 粉粒物料运输车 </a> <a target="_top" href="/103005-<%=factoryid%>-0.htm"> 混凝土布料设备 </a> <a target="_top" href="/103006-<%=factoryid%>-0.htm"> 混凝土搅拌运输车 </a> <a target="_top" href="/103015-<%=factoryid%>-0.htm"> 其它混凝土设备 </a> <a target="_top" href="/103012-<%=factoryid%>-0.htm"> 干混砂浆生产线 </a> <a target="_top" href="/103011-<%=factoryid%>-0.htm"> 沥青砂浆车 </a> <a target="_top" href="/103014-<%=factoryid%>-0.htm"> 干混砂浆背罐车 </a> <a target="_top" href="/103002-<%=factoryid%>-0.htm"> 混凝土搅拌设备 </a> <a target="_top" href="/103001-<%=factoryid%>-0.htm"> 混凝土泵车 </a> <a target="_top" href="/103010-<%=factoryid%>-0.htm"> 喷湿机 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/104-<%=factoryid%>-0.htm"><strong style="color:#3355AC"> 筑养路机械 </strong></a> <br>
                  <a target="_top" href="/104006-<%=factoryid%>-0.htm"> 稳定土拌合机 </a> <a target="_top" href="/104005-<%=factoryid%>-0.htm"> 铣刨机 </a> <a target="_top" href="/104008-<%=factoryid%>-0.htm"> 稳定土厂拌设备 </a> <a target="_top" href="/104007-<%=factoryid%>-0.htm"> 沥青混合料搅拌设备 </a> <a target="_top" href="/104009-<%=factoryid%>-0.htm"> 沥青搅拌站 </a> <a target="_top" href="/104004-<%=factoryid%>-0.htm"> 其它路面机械 </a> <a target="_top" href="/104001-<%=factoryid%>-0.htm"> 摊铺机 </a> <a target="_top" href="/104002-<%=factoryid%>-0.htm"> 养护机械 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/105-<%=factoryid%>-0.htm"><strong style="color:#3355AC"> 桩工机械</strong> </a> <br>
                  <a target="_top" href="/105017-<%=factoryid%>-0.htm"> 强夯机 </a> <a target="_top" href="/105018-<%=factoryid%>-0.htm"> 长螺旋钻孔机 </a> <a target="_top" href="/105009-<%=factoryid%>-0.htm"> 液压静力压桩机 </a> <a target="_top" href="/105019-<%=factoryid%>-0.htm"> 多功能钻机 </a> <a target="_top" href="/105007-<%=factoryid%>-0.htm"> 连续墙抓斗 </a> <a target="_top" href="/105028-<%=factoryid%>-0.htm"> 截桩机/破桩机 </a> <a target="_top" href="/105011-<%=factoryid%>-0.htm"> 打桩机 </a> <a target="_top" href="/105016-<%=factoryid%>-0.htm"> 连续墙钻机 </a> <a target="_top" href="/105015-<%=factoryid%>-0.htm"> 打桩锤 </a> <a target="_top" href="/105027-<%=factoryid%>-0.htm"> 其它桩工机械 </a> <a target="_top" href="/105026-<%=factoryid%>-0.htm"> 多轴钻孔机 </a> <a target="_top" href="/105013-<%=factoryid%>-0.htm"> 液压步履式桩架 </a> <a target="_top" href="/105003-<%=factoryid%>-0.htm"> 旋挖钻机 </a> <a target="_top" href="/105004-<%=factoryid%>-0.htm"> 潜孔钻机 </a> <a target="_top" href="/105005-<%=factoryid%>-0.htm"> 水平定向钻 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/106-<%=factoryid%>-0.htm"><strong style="color:#3355AC"> 压实机械 </strong></a> <br>
                  <a target="_top" href="/106004-<%=factoryid%>-0.htm"> 夯实机 </a> <a target="_top" href="/106003-<%=factoryid%>-0.htm"> 压实机 </a> <a target="_top" href="/106001-<%=factoryid%>-0.htm"> 压路机 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/107-<%=factoryid%>-0.htm"> <strong style="color:#3355AC"> 叉车</strong> </a> <br>
                  <a target="_top" href="/107010-<%=factoryid%>-0.htm"> 专用叉车 </a> <a target="_top" href="/107001-<%=factoryid%>-0.htm"> 内燃叉车 </a> <a target="_top" href="/107003-<%=factoryid%>-0.htm"> 电动叉车 </a> <a target="_top" href="/107005-<%=factoryid%>-0.htm"> 仓储叉车 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/109-<%=factoryid%>-0.htm"><strong style="color:#3355AC"> 桥梁机械 </strong></a> <br>
                  <a target="_top" href="/109004-<%=factoryid%>-0.htm"> 提梁机 </a> <a target="_top" href="/109005-<%=factoryid%>-0.htm"> 检测车 </a> <a target="_top" href="/109002-<%=factoryid%>-0.htm"> 运梁车 </a> <a target="_top" href="/109006-<%=factoryid%>-0.htm"> 砂浆车 </a> <a target="_top" href="/109001-<%=factoryid%>-0.htm"> 架桥机 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/110-<%=factoryid%>-0.htm"> <strong style="color:#3355AC"> 地下及矿山机械</strong> </a> <br>
                  <a target="_top" href="/110010-<%=factoryid%>-0.htm"> 凿岩钻车 </a> <a target="_top" href="/110008-<%=factoryid%>-0.htm"> 凿岩台车 </a> <a target="_top" href="/110009-<%=factoryid%>-0.htm"> 破碎机 </a> <a target="_top" href="/110011-<%=factoryid%>-0.htm"> 凿岩机和钻机 </a> <a target="_top" href="/110012-<%=factoryid%>-0.htm"> 筛分机 </a> <a target="_top" href="/110013-<%=factoryid%>-0.htm"> 装载及搬运设备 </a> <a target="_top" href="/110014-<%=factoryid%>-0.htm"> 连续采煤机和隧道掘进机 </a> <a target="_top" href="/110005-<%=factoryid%>-0.htm"> 采煤机 </a> <a target="_top" href="/110015-<%=factoryid%>-0.htm"> 输送和辅助设备 </a> <a target="_top" href="/110002-<%=factoryid%>-0.htm"> 矿用掘进机 </a> <a target="_top" href="/110016-<%=factoryid%>-0.htm"> 全液压凿岩钻机 </a> <a target="_top" href="/110017-<%=factoryid%>-0.htm"> 隧道轨道设备 </a> <a target="_top" href="/110001-<%=factoryid%>-0.htm"> 盾构掘进机 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/111-<%=factoryid%>-0.htm"><strong style="color:#3355AC"> 港口机械</strong> </a> <br>
                  <a target="_top" href="/111003-<%=factoryid%>-0.htm"> 吊具 </a> <a target="_top" href="/111001-<%=factoryid%>-0.htm"> 正面吊 </a> <a target="_top" href="/111002-<%=factoryid%>-0.htm"> 堆高机 </a> <a target="_top" href="/111007-<%=factoryid%>-0.htm"> 推耙机 </a> <a target="_top" href="/111006-<%=factoryid%>-0.htm"> 场桥 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/113-<%=factoryid%>-0.htm"> <strong style="color:#3355AC"> 破碎设备</strong> </a> <br>
                  <a target="_top" href="/113002-<%=factoryid%>-0.htm"> 液压剪 </a> <a target="_top" href="/113001-<%=factoryid%>-0.htm"> 破碎锤 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/118-<%=factoryid%>-0.htm"> <strong style="color:#3355AC"> 专用汽车</strong> </a> <br>
                  <a target="_top" href="/118004-<%=factoryid%>-0.htm"> 牵引车 </a> <a target="_top" href="/118002-<%=factoryid%>-0.htm"> 专用车辆 </a> <a target="_top" href="/118003-<%=factoryid%>-0.htm"> 消防车 </a> </div>
                <div class="pllist"> <a target="_top" class="plfl" href="/119-<%=factoryid%>-0.htm"><strong style="color:#3355AC"> 煤炭机械</strong> </a> <br>
                  <a target="_top" href="/119001-<%=factoryid%>-0.htm"> 煤炭机械 </a> </div>

</cache:cache>
