<%@ page language="java" import="java.util.*,com.jerehnet.util.common.*,org.apache.commons.httpclient.*,org.apache.commons.httpclient.methods.*" pageEncoding="UTF-8"%>
		   			<li title="徐工挖掘机"><a title="徐工挖掘机" href="?factory=209&catalog=101001">徐工挖掘机</a></li>
		   			<li title="徐工装载机"><a title="徐工装载机" href="?factory=209&catalog=101002">徐工装载机</a></li>
		   			<li title="徐工平地机"><a title="徐工平地机" href="?factory=209&catalog=101005">徐工平地机</a></li>
		   			<li title="徐工自卸卡车"><a title="徐工自卸卡车" href="?factory=209&catalog=101008">徐工自卸卡车</a></li>
		   			<li title="徐工起重机"><a title="徐工起重机" href="?factory=209&catalog=102">徐工起重机</a></li>
		   			<li title="徐工塔式起重机"><a title="徐工塔式起重机" href="?factory=209&catalog=102002">徐工塔式起重机</a></li>
		   			<li title="徐工高空作业平台"><a title="徐工高空作业平台" href="?factory=209&catalog=102003">徐工高空作业平台</a></li>
		   			<li title="徐工随车起重机"><a title="徐工随车起重机" href="?factory=209&catalog=102006">徐工随车起重机</a></li>
		   			<li title="徐工汽车起重机"><a title="徐工汽车起重机" href="?factory=209&catalog=102007">徐工汽车起重机</a></li>
		   			<li title="徐工履带式起重机"><a title="徐工履带式起重机" href="?factory=209&catalog=102008">徐工履带式起重机</a></li>
		   			<li title="徐工高空作业车"><a title="徐工高空作业车" href="?factory=209&catalog=102010">徐工高空作业车</a></li>
		   			<li title="徐工伸缩臂叉装机"><a title="徐工伸缩臂叉装机" href="?factory=209&catalog=102012">徐工伸缩臂叉装机</a></li>
		   			<li title="徐工混凝土泵车"><a title="徐工混凝土泵车" href="?factory=209&catalog=103001">徐工混凝土泵车</a></li>
		   			<li title="徐工混凝土搅拌设备"><a title="徐工混凝土搅拌设备" href="?factory=209&catalog=103002">徐工混凝土搅拌设备</a></li>
		   			<li title="徐工粉粒物料运输车"><a title="徐工粉粒物料运输车" href="?factory=209&catalog=103009">徐工粉粒物料运输车</a></li>
		   			<li title="徐工其它混凝土设备"><a title="徐工其它混凝土设备" href="?factory=209&catalog=103015">徐工其它混凝土设备</a></li>
		   			<li title="徐工车载泵"><a title="徐工车载泵" href="?factory=209&catalog=103017">徐工车载泵</a></li>
		   			<li title="徐工拖泵"><a title="徐工拖泵" href="?factory=209&catalog=103018">徐工拖泵</a></li>
		   			<li title="徐工混凝土搅拌运输车"><a title="徐工混凝土搅拌运输车" href="?factory=209&catalog=103019">徐工混凝土搅拌运输车</a></li>
		   			<li title="徐工摊铺机"><a title="徐工摊铺机" href="?factory=209&catalog=104001">徐工摊铺机</a></li>
		   			<li title="徐工养护机械"><a title="徐工养护机械" href="?factory=209&catalog=104002">徐工养护机械</a></li>
		   			<li title="徐工其它路面机械"><a title="徐工其它路面机械" href="?factory=209&catalog=104004">徐工其它路面机械</a></li>
		   			<li title="徐工铣刨机"><a title="徐工铣刨机" href="?factory=209&catalog=104005">徐工铣刨机</a></li>
		   			<li title="徐工稳定土拌合机"><a title="徐工稳定土拌合机" href="?factory=209&catalog=104006">徐工稳定土拌合机</a></li>
		   			<li title="徐工沥青混合料搅拌设备"><a title="徐工沥青混合料搅拌设备" href="?factory=209&catalog=104007">徐工沥青混合料搅拌设备</a></li>
		   			<li title="徐工稳定土厂拌设备"><a title="徐工稳定土厂拌设备" href="?factory=209&catalog=104008">徐工稳定土厂拌设备</a></li>
		   			<li title="徐工旋挖钻机"><a title="徐工旋挖钻机" href="?factory=209&catalog=105003">徐工旋挖钻机</a></li>
		   			<li title="徐工水平定向钻"><a title="徐工水平定向钻" href="?factory=209&catalog=105005">徐工水平定向钻</a></li>
		   			<li title="徐工连续墙抓斗"><a title="徐工连续墙抓斗" href="?factory=209&catalog=105007">徐工连续墙抓斗</a></li>
		   			<li title="徐工强夯机"><a title="徐工强夯机" href="?factory=209&catalog=105017">徐工强夯机</a></li>
		   			<li title="徐工其它桩工机械"><a title="徐工其它桩工机械" href="?factory=209&catalog=105027">徐工其它桩工机械</a></li>
		   			<li title="徐工压路机"><a title="徐工压路机" href="?factory=209&catalog=106001">徐工压路机</a></li>
		   			<li title="徐工压实机"><a title="徐工压实机" href="?factory=209&catalog=106003">徐工压实机</a></li>
		   			<li title="徐工内燃叉车"><a title="徐工内燃叉车" href="?factory=209&catalog=107001">徐工内燃叉车</a></li>
		   			<li title="徐工架桥机"><a title="徐工架桥机" href="?factory=209&catalog=109001">徐工架桥机</a></li>
		   			<li title="徐工运梁车"><a title="徐工运梁车" href="?factory=209&catalog=109002">徐工运梁车</a></li>
		   			<li title="徐工提梁机"><a title="徐工提梁机" href="?factory=209&catalog=109004">徐工提梁机</a></li>
		   			<li title="徐工检测车"><a title="徐工检测车" href="?factory=209&catalog=109005">徐工检测车</a></li>
		   			<li title="徐工砂浆车"><a title="徐工砂浆车" href="?factory=209&catalog=109006">徐工砂浆车</a></li>
		   			<li title="徐工矿用掘进机"><a title="徐工矿用掘进机" href="?factory=209&catalog=110002">徐工矿用掘进机</a></li>
		   			<li title="徐工凿岩台车"><a title="徐工凿岩台车" href="?factory=209&catalog=110008">徐工凿岩台车</a></li>
		   			<li title="徐工专用车辆"><a title="徐工专用车辆" href="?factory=209&catalog=118002">徐工专用车辆</a></li>
		   			<li title="徐工消防车"><a title="徐工消防车" href="?factory=209&catalog=118003">徐工消防车</a></li>
		   			<li title="徐工牵引车"><a title="徐工牵引车" href="?factory=209&catalog=118004">徐工牵引车</a></li>
