document.writeln("<div class=\"visit_21sun\"><a target=\"_blank\" href=\"http://www.21-sun.com\" title=\"访问中国工程机械商贸网首页\"><img src=\"/images/n_toppoint.gif\" align=\"absmiddle\" /> 访问中国工程机械商贸网首页</a></div>");
document.writeln("    <ul class=\"tlRight\">");
document.writeln("      <li class=\"tl\"><a onclick=\"addCookie();\" href=\"javascript:;\"  rel=\"nofollow\">加入收藏</a></li>");
document.writeln("      <li class=\"tl\"><a onclick=\"setHomePage();\" href=\"javascript:;\"  rel=\"nofollow\">设为首页</a></li>");
document.writeln("      <li class=\"tl\"><span onclick=\"window.open(\'http://www.21-sun.com/service/\');\" style=\"cursor: pointer;\">企业服务</span></li>");
document.writeln("      <li class=\"tl\"><span onclick=\"window.open(\'http://aboutus.21-sun.com/contact/\');\" style=\"cursor: pointer;\">客服中心</span></li>");
document.writeln("      <li class=\"guide\"><span class=\"gt\">网站导航</span>");
document.writeln("        <ul>");
document.writeln("          <li><span onclick=\"window.open(\'http://product.21-sun.com/\');\" style=\"cursor: pointer;\">整机市场</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://news.21-sun.com/\');\" style=\"cursor: pointer;\">行业动态</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://www.21-sun.com/part/\');\" style=\"cursor: pointer;\">配件市场</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://data.21-sun.com/\');\" style=\"cursor: pointer;\">数据分析</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://www.21-used.com/\');\" style=\"cursor: pointer;\">二手市场</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://www.21-sun.com/bidding/\');\" style=\"cursor: pointer;\">招 投 标</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://www.21-rent.com/\');\" style=\"cursor: pointer;\">租赁调剂</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://stock.21-sun.com/\');\" style=\"cursor: pointer;\">行业股市</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://www.21part.com/\');\" style=\"cursor: pointer;\">配件商城</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://www.21-cmjob.com/\');\" style=\"cursor: pointer;\">人才招聘</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://www.21peitao.com/\');\" style=\"cursor: pointer;\">配套件</span></li>");
document.writeln("          <li><span onclick=\"window.open(\'http://news.21-sun.com/news/default.shtml\');\" style=\"cursor: pointer;\">企业服务</span></li>");
document.writeln("        </ul>");
document.writeln("      </li>");
document.writeln("      <li class=\"blog\"><a rel=\"nofollow\" href=\"http://weibo.com/3w21sun\" target=\"_blank\">21-sun官方微博</a></li>");
document.writeln("    </ul>");
document.writeln("  </div>");