<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%><%@page import="com.jerehnet.util.common.CommonString"%><%@page import="com.jerehnet.util.dbutil.DBHelper"%><%@ page session="false" %><%@ taglib uri="/WEB-INF/classes/oscache.tld" prefix="cache"%>
<cache:cache cron="* * */1 * *">
<%
	String province = CommonString.getFormatPara(request.getParameter("province"));
	String city = CommonString.getFormatPara(request.getParameter("city"));

%>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_101_0.shtm" class="plfl" target="_top"> <strong style="color:#3355AC">土方机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_101003_0.shtm" target="_top"> 推土机 </a> <a href="/<%=province%>_<%=city%>_0_101002_0.shtm" target="_top"> 装载机 </a> <a href="/<%=province%>_<%=city%>_0_101001_0.shtm" target="_top"> 挖掘机 </a> <a href="/<%=province%>_<%=city%>_0_101005_0.shtm" target="_top"> 平地机 </a> <a href="/<%=province%>_<%=city%>_0_101004_0.shtm" target="_top"> 铲运机 </a> <a href="/<%=province%>_<%=city%>_0_101008_0.shtm" target="_top"> 自卸卡车 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_102_0.shtm" class="plfl" target="_top"> <strong style="color:#3355AC">起重机 </strong></a> <br/>
                <a href="/<%=province%>_<%=city%>_0_102013_0.shtm" target="_top"> 桥梁式起重机 </a> <a href="/<%=province%>_<%=city%>_0_102012_0.shtm" target="_top"> 伸缩臂叉装机 </a> <a href="/<%=province%>_<%=city%>_0_102002_0.shtm" target="_top"> 塔式起重机 </a> <a href="/<%=province%>_<%=city%>_0_102011_0.shtm" target="_top"> 施工升降机 </a> <a href="/<%=province%>_<%=city%>_0_102010_0.shtm" target="_top"> 高空作业车 </a> <a href="/<%=province%>_<%=city%>_0_102007_0.shtm" target="_top"> 汽车起重机 </a> <a href="/<%=province%>_<%=city%>_0_102008_0.shtm" target="_top"> 履带式起重机 </a> <a href="/<%=province%>_<%=city%>_0_102006_0.shtm" target="_top"> 随车起重机 </a> <a href="/<%=province%>_<%=city%>_0_102003_0.shtm" target="_top"> 高空作业平台 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_103_0.shtm" class="plfl" target="_top"><strong style="color:#3355AC"> 混凝土机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_103008_0.shtm" target="_top"> 干粉砂浆生产设备 </a> <a href="/<%=province%>_<%=city%>_0_103009_0.shtm" target="_top"> 粉粒物料运输车 </a> <a href="/<%=province%>_<%=city%>_0_103005_0.shtm" target="_top"> 混凝土布料设备 </a> <a href="/<%=province%>_<%=city%>_0_103006_0.shtm" target="_top"> 混凝土搅拌运输车 </a> <a href="/<%=province%>_<%=city%>_0_103015_0.shtm" target="_top"> 其它混凝土设备 </a> <a href="/<%=province%>_<%=city%>_0_103012_0.shtm" target="_top"> 干混砂浆生产线 </a> <a href="/<%=province%>_<%=city%>_0_103011_0.shtm" target="_top"> 沥青砂浆车 </a> <a href="/<%=province%>_<%=city%>_0_103014_0.shtm" target="_top"> 干混砂浆背罐车 </a> <a href="/<%=province%>_<%=city%>_0_103002_0.shtm" target="_top"> 混凝土搅拌设备 </a> <a href="/<%=province%>_<%=city%>_0_103001_0.shtm" target="_top"> 混凝土泵车 </a> <a href="/<%=province%>_<%=city%>_0_103010_0.shtm" target="_top"> 喷湿机 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_104_0.shtm" class="plfl" target="_top"> <strong style="color:#3355AC">筑养路机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_104006_0.shtm" target="_top"> 稳定土拌合机 </a> <a href="/<%=province%>_<%=city%>_0_104005_0.shtm" target="_top"> 铣刨机 </a> <a href="/<%=province%>_<%=city%>_0_104008_0.shtm" target="_top"> 稳定土厂拌设备 </a> <a href="/<%=province%>_<%=city%>_0_104007_0.shtm" target="_top"> 沥青混合料搅拌设备 </a> <a href="/<%=province%>_<%=city%>_0_104009_0.shtm" target="_top"> 沥青搅拌站 </a> <a href="/<%=province%>_<%=city%>_0_104004_0.shtm" target="_top"> 其它路面机械 </a> <a href="/<%=province%>_<%=city%>_0_104001_0.shtm" target="_top"> 摊铺机 </a> <a href="/<%=province%>_<%=city%>_0_104002_0.shtm" target="_top"> 养护机械 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_105_0.shtm" class="plfl" target="_top"> <strong style="color:#3355AC">桩工机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_105017_0.shtm" target="_top"> 强夯机 </a> <a href="/<%=province%>_<%=city%>_0_105018_0.shtm" target="_top"> 长螺旋钻孔机 </a> <a href="/<%=province%>_<%=city%>_0_105009_0.shtm" target="_top"> 液压静力压桩机 </a> <a href="/<%=province%>_<%=city%>_0_105019_0.shtm" target="_top"> 多功能钻机 </a> <a href="/<%=province%>_<%=city%>_0_105007_0.shtm" target="_top"> 连续墙抓斗 </a> <a href="/<%=province%>_<%=city%>_0_105028_0.shtm" target="_top"> 截桩机/破桩机 </a> <a href="/<%=province%>_<%=city%>_0_105011_0.shtm" target="_top"> 打桩机 </a> <a href="/<%=province%>_<%=city%>_0_105016_0.shtm" target="_top"> 连续墙钻机 </a> <a href="/<%=province%>_<%=city%>_0_105015_0.shtm" target="_top"> 打桩锤 </a> <a href="/<%=province%>_<%=city%>_0_105027_0.shtm" target="_top"> 其它桩工机械 </a> <a href="/<%=province%>_<%=city%>_0_105026_0.shtm" target="_top"> 多轴钻孔机 </a> <a href="/<%=province%>_<%=city%>_0_105013_0.shtm" target="_top"> 液压步履式桩架 </a> <a href="/<%=province%>_<%=city%>_0_105003_0.shtm" target="_top"> 旋挖钻机 </a> <a href="/<%=province%>_<%=city%>_0_105004_0.shtm" target="_top"> 潜孔钻机 </a> <a href="/<%=province%>_<%=city%>_0_105005_0.shtm" target="_top"> 水平定向钻 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_106_0.shtm" class="plfl" target="_top"><strong style="color:#3355AC"> 压实机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_106004_0.shtm" target="_top"> 夯实机 </a> <a href="/<%=province%>_<%=city%>_0_106003_0.shtm" target="_top"> 压实机 </a> <a href="/<%=province%>_<%=city%>_0_106001_0.shtm" target="_top"> 压路机 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_107_0.shtm" class="plfl" target="_top"> <strong style="color:#3355AC">叉车</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_107010_0.shtm" target="_top"> 专用叉车 </a> <a href="/<%=province%>_<%=city%>_0_107001_0.shtm" target="_top"> 内燃叉车 </a> <a href="/<%=province%>_<%=city%>_0_107003_0.shtm" target="_top"> 电动叉车 </a> <a href="/<%=province%>_<%=city%>_0_107005_0.shtm" target="_top"> 仓储叉车 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_109_0.shtm" class="plfl" target="_top"><strong style="color:#3355AC"> 桥梁机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_109004_0.shtm" target="_top"> 提梁机 </a> <a href="/<%=province%>_<%=city%>_0_109005_0.shtm" target="_top"> 检测车 </a> <a href="/<%=province%>_<%=city%>_0_109002_0.shtm" target="_top"> 运梁车 </a> <a href="/<%=province%>_<%=city%>_0_109006_0.shtm" target="_top"> 砂浆车 </a> <a href="/<%=province%>_<%=city%>_0_109001_0.shtm" target="_top"> 架桥机 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_110_0.shtm" class="plfl" target="_top"><strong style="color:#3355AC"> 地下及矿山机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_110010_0.shtm" target="_top"> 凿岩钻车 </a> <a href="/<%=province%>_<%=city%>_0_110008_0.shtm" target="_top"> 凿岩台车 </a> <a href="/<%=province%>_<%=city%>_0_110009_0.shtm" target="_top"> 破碎机 </a> <a href="/<%=province%>_<%=city%>_0_110011_0.shtm" target="_top"> 凿岩机和钻机 </a> <a href="/<%=province%>_<%=city%>_0_110012_0.shtm" target="_top"> 筛分机 </a> <a href="/<%=province%>_<%=city%>_0_110013_0.shtm" target="_top"> 装载及搬运设备 </a> <a href="/<%=province%>_<%=city%>_0_110014_0.shtm" target="_top"> 连续采煤机和隧道掘进机 </a> <a href="/<%=province%>_<%=city%>_0_110005_0.shtm" target="_top"> 采煤机 </a> <a href="/<%=province%>_<%=city%>_0_110015_0.shtm" target="_top"> 输送和辅助设备 </a> <a href="/<%=province%>_<%=city%>_0_110002_0.shtm" target="_top"> 矿用掘进机 </a> <a href="/<%=province%>_<%=city%>_0_110016_0.shtm" target="_top"> 全液压凿岩钻机 </a> <a href="/<%=province%>_<%=city%>_0_110017_0.shtm" target="_top"> 隧道轨道设备 </a> <a href="/<%=province%>_<%=city%>_0_110001_0.shtm" target="_top"> 盾构掘进机 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_111_0.shtm" class="plfl" target="_top"> <strong style="color:#3355AC">港口机械 </strong></a> <br/>
                <a href="/<%=province%>_<%=city%>_0_111003_0.shtm" target="_top"> 吊具 </a> <a href="/<%=province%>_<%=city%>_0_111001_0.shtm" target="_top"> 正面吊 </a> <a href="/<%=province%>_<%=city%>_0_111002_0.shtm" target="_top"> 堆高机 </a> <a href="/<%=province%>_<%=city%>_0_111007_0.shtm" target="_top"> 推耙机 </a> <a href="/<%=province%>_<%=city%>_0_111006_0.shtm" target="_top"> 场桥 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_113_0.shtm" class="plfl" target="_top"> <strong style="color:#3355AC">破碎设备</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_113002_0.shtm" target="_top"> 液压剪 </a> <a href="/<%=province%>_<%=city%>_0_113001_0.shtm" target="_top"> 破碎锤 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_118_0.shtm" class="plfl" target="_top"><strong style="color:#3355AC"> 专用汽车</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_118004_0.shtm" target="_top"> 牵引车 </a> <a href="/<%=province%>_<%=city%>_0_118002_0.shtm" target="_top"> 专用车辆 </a> <a href="/<%=province%>_<%=city%>_0_118003_0.shtm" target="_top"> 消防车 </a> </div>
              <div class="pllist"> <a href="/<%=province%>_<%=city%>_0_119_0.shtm" class="plfl" target="_top"><strong style="color:#3355AC"> 煤炭机械</strong> </a> <br/>
                <a href="/<%=province%>_<%=city%>_0_119001_0.shtm" target="_top"> 煤炭机械 </a> </div>
<!--代理商列表结束-->
</cache:cache>