<%@ page language="java" import="java.util.*,com.jerehnet.util.common.*,org.apache.commons.httpclient.*,org.apache.commons.httpclient.methods.*" pageEncoding="UTF-8"%>
		   			<li title="山推装载机"><a title="山推装载机" href="?factory=144&catalog=101002">山推装载机</a></li>
		   			<li title="山推推土机"><a title="山推推土机" href="?factory=144&catalog=101003">山推推土机</a></li>
		   			<li title="山推平地机"><a title="山推平地机" href="?factory=144&catalog=101005">山推平地机</a></li>
		   			<li title="山推起重机"><a title="山推起重机" href="?factory=144&catalog=102">山推起重机</a></li>
		   			<li title="山推高空作业车"><a title="山推高空作业车" href="?factory=144&catalog=102010">山推高空作业车</a></li>
		   			<li title="山推混凝土泵车"><a title="山推混凝土泵车" href="?factory=144&catalog=103001">山推混凝土泵车</a></li>
		   			<li title="山推混凝土搅拌设备"><a title="山推混凝土搅拌设备" href="?factory=144&catalog=103002">山推混凝土搅拌设备</a></li>
		   			<li title="山推车载泵"><a title="山推车载泵" href="?factory=144&catalog=103017">山推车载泵</a></li>
		   			<li title="山推拖泵"><a title="山推拖泵" href="?factory=144&catalog=103018">山推拖泵</a></li>
		   			<li title="山推混凝土搅拌运输车"><a title="山推混凝土搅拌运输车" href="?factory=144&catalog=103019">山推混凝土搅拌运输车</a></li>
		   			<li title="山推摊铺机"><a title="山推摊铺机" href="?factory=144&catalog=104001">山推摊铺机</a></li>
		   			<li title="山推旋挖钻机"><a title="山推旋挖钻机" href="?factory=144&catalog=105003">山推旋挖钻机</a></li>
		   			<li title="山推压路机"><a title="山推压路机" href="?factory=144&catalog=106001">山推压路机</a></li>
		   			<li title="山推压实机"><a title="山推压实机" href="?factory=144&catalog=106003">山推压实机</a></li>
		   			<li title="山推内燃叉车"><a title="山推内燃叉车" href="?factory=144&catalog=107001">山推内燃叉车</a></li>
		   			<li title="山推电动叉车"><a title="山推电动叉车" href="?factory=144&catalog=107003">山推电动叉车</a></li>
		   			<li title="山推推耙机"><a title="山推推耙机" href="?factory=144&catalog=111007">山推推耙机</a></li>
		   			<li title="山推消防车"><a title="山推消防车" href="?factory=144&catalog=118003">山推消防车</a></li>
		   			<li title="山推牵引车"><a title="山推牵引车" href="?factory=144&catalog=118004">山推牵引车</a></li>
